server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: blocker-microservice
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org:
      springframework:
        security: DEBUG
