server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:127.0.0.1:8087
    ip-address: 127.0.0.1
    hostname: localhost
    non-secure-port: 8087
    status-page-url: http://127.0.0.1:8087/actuator/info
    health-check-url: http://127.0.0.1:8087/actuator/health
    home-page-url: http://127.0.0.1:8087/
spring:
  application:
    name: blocker-microservice
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org:
      springframework:
        security: DEBUG
