server:
  port: 8088

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts-microservice
              uri: lb://accounts-microservice
              predicates:
                    - Path=/accounts/**
              filters:
                - StripPrefix=1
            - id: cash-microservice
              uri: lb://cash-microservice
              predicates:
                - Path=/cash/**
              filters:
                - StripPrefix=1
            - id: transfer-microservice
              uri: lb://transfer-microservice
              predicates:
                - Path=/transfer/**
              filters:
                - StripPrefix=1
            - id: exchange-microservice
              uri: lb://exchange-microservice
              predicates:
                - Path=/exchange/**
              filters:
                - StripPrefix=1
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:127.0.0.1:8088
    ip-address: 127.0.0.1
    hostname: localhost
    non-secure-port: 8088
    status-page-url: http://127.0.0.1:8088/actuator/info
    health-check-url: http://127.0.0.1:8088/actuator/health
    home-page-url: http://127.0.0.1:8088/