server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.application.name}  
    non-secure-port: 8082
    status-page-url: /actuator/info
    health-check-url: /actuator/health
spring:
  kafka:
    producer:
      bootstrap-servers: kafka.default.svc.cluster.local:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master
      client:
        registration:
          cash-microservice:
            client-id: cash-microservice
            client-secret: a
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org:
      springframework:
        security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
