server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.application.name}  
    non-secure-port: 8083
    status-page-url: /actuator/info
    health-check-url: /actuator/health
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master
      client:
        registration:
          notifications-microservice:
            client-id: notifications-microservice
            client-secret: a
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org:
      springframework:
        security: DEBUG
