server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:127.0.0.1:8083
    ip-address: 127.0.0.1
    hostname: localhost
    non-secure-port: 8083
    status-page-url: http://127.0.0.1:8083/actuator/info
    health-check-url: http://127.0.0.1:8083/actuator/health
    home-page-url: http://127.0.0.1:8083/
spring:
  application:
    name: notifications-microservice
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org:
      springframework:
        security: DEBUG
