server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:127.0.0.1:8089
    ip-address: 127.0.0.1
    hostname: localhost
    non-secure-port: 8089
    status-page-url: http://127.0.0.1:8089/actuator/info
    health-check-url: http://127.0.0.1:8089/actuator/health
    home-page-url: http://127.0.0.1:8089/

jackson:
  property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        security: DEBUG
