input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["logs-microservices"]
    group_id => "yandex-group"
    decorate_events => true
  }
}

filter {
  grok {
    match => { 
      "message" => "%{TIME:time} %{LOGLEVEL:log_level} \[%{DATA:service}\] \[%{DATA:trace}\] - %{GREEDYDATA:log_message}" 
    }
  }
  if ![service] or [service] == "" {
    drop { }
  }
if ![log_level] == "DEBUG" {
    drop { }
  }
}

output {
  stdout {
    codec => rubydebug
  }

  #elasticsearch {
  #  hosts => ["http://elasticsearch:9200"]
  #  index => "bankapp-logs-%{+YYYY.MM.dd}"
  #  user => "1"   
  #  password => "1"
  #}
}
